export enum EFormasPagamento {
    BOLETO = 'BOLETO',
    CARTAO_CREDITO = 'CARTAO_CREDITO',
    CARTAO_DEBITO = 'CARTAO_DEBITO',
    DINHEIRO = 'DINHEIRO',
    PIX = 'PIX',
}

export enum ESetores {
    ADMINISTRADOR = 'ADMINISTRADOR',
    CD = 'CD',
    COMERCIAL = 'COMERCIAL',
    CUIDADO_DE_ALUNOS = 'CUIDADO_DE_ALUNOS',
    EVENTOS = 'EVENTOS',
    EXPANSAO = 'EXPANSAO',
    FINANCEIRO = 'FINANCEIRO',
    GH = 'GH',
    JURIDICO = 'JURIDICO',
    MARKETING = 'MARKETING',
    TECNOLOGIA = 'TECNOLOGIA',
}

export enum EFuncoes {
    ADMINISTRADOR = 'ADMINISTRADOR',
    ADVOGADO = 'ADVOGADO',
    COLABORADOR = 'COLABORADOR',
    DESENVOLVEDOR = 'DESENVOLVEDOR',
    DJ = 'DJ',
    ESTAGIARIO = 'ESTAGIARIO',
    LIDER = 'LIDER',
    LIDER_DE_EVENTOS = 'LIDER_DE_EVENTOS',
    PALESTRANTE = 'PALESTRANTE',
    STAFF = 'STAFF',
    VENDEDOR = 'VENDEDOR',
}

export enum EOrigemAlunos {
    ALUNO_BONUS = 'ALUNO_BONUS',
    COMPROU_INGRESSO = 'COMPROU_INGRESSO',
}

export enum EPresencaTurmas {
    NO_SHOW = 'NO_SHOW',
    PRESENTE = 'PRESENTE',
}

export enum EStatusAlunosGeral {
    ATIVO = 'ATIVO',
    INADIMPLENTE = 'INADIMPLENTE',
    INATIVO = 'INATIVO',
    PENDENTE = 'PENDENTE',
    SUSPENSO = 'SUSPENSO',
    CANCELADO = 'CANCELADO',
}

export enum EStatusAlunosTurmas {
    AGUARDANDO_CHECKIN = 'AGUARDANDO_CHECKIN',
    CANCELADO = 'CANCELADO',
    CHECKIN_REALIZADO = 'CHECKIN_REALIZADO',
    FALTA_ENVIAR_LINK_CHECKIN = 'FALTA_ENVIAR_LINK_CHECKIN',
}

export enum EStatusAssinaturasContratos {
    ASSINADO = 'ASSINADO',
    ASSINATURA_PENDENTE = 'ASSINATURA_PENDENTE',
}

export enum EStatusTurmas {
    ENCERRADA = 'ENCERRADA',
    INSCRICOES_ABERTAS = 'INSCRICOES_ABERTAS',
    INSCRICOES_PAUSADAS = 'INSCRICOES_PAUSADAS',
}

export enum ETiposProdutos {
    LIVRO = 'LIVRO',
    MATERIAL_ESCRITORIO = 'MATERIAL_ESCRITORIO',
    OUTRO = 'OUTRO',
    VESTUARIO = 'VESTUARIO',
}

export enum ETipoDocumento {
    CONTRATO = 'CONTRATO',
    TERMO = 'TERMO',
}
