export enum EFormasPagamento {
    BOLETO = 'BOLETO',
    CARTAO_CREDITO = 'CARTAO_CREDITO',
    CARTAO_DEBITO = 'CARTAO_DEBITO',
    DINHEIRO = 'DINHEIRO',
    PIX = 'PIX',
}

export enum ESetores {
    ADMINISTRADOR = 'ADMINISTRADOR',
    CD = 'CD',
    COMERCIAL = 'COMERCIAL',
    CUIDADO_DE_ALUNOS = 'CUIDADO_DE_ALUNOS',
    EVENTOS = 'EVENTOS',
    EXPANSAO = 'EXPANSAO',
    EXPANSAO_NEGOCIOS = 'EXPANSAO_NEGOCIOS',
    FINANCEIRO = 'FINANCEIRO',
    GESTAO_DE_CONTAS = 'GESTAO_DE_CONTAS',
    GH = 'GH',
    IAM_STORE = 'IAM_STORE',
    LEGACY_COFFEE = 'LEGACY_COFFEE',
    LIMPEZA = 'LIMPEZA',
    JURIDICO = 'JURIDICO',
    MANUTENCAO = 'MANUTENCAO',
    MARKETING = 'MARKETING',
    P7 = 'P7',
    TECNOLOGIA = 'TECNOLOGIA',
}

export enum EFuncoes {
    ADMINISTRADOR = 'ADMINISTRADOR',
    ARQUITETO = 'ARQUITETO',
    ADVOGADO = 'ADVOGADO',
    CLIPADOR = 'CLIPADOR',
    COLABORADOR = 'COLABORADOR',
    COPYWRITER = 'COPYWRITER',
    DESENVOLVEDOR = 'DESENVOLVEDOR',
    DESIGNER_GRAFICO = 'DESIGNER_GRAFICO',
    DJ = 'DJ',
    EDICAO_DE_VIDEO = 'EDICAO_DE_VIDEO',
    ESTAGIARIO = 'ESTAGIARIO',
    FOTOGRAFO = 'FOTOGRAFO',
    INSIDE_SALES = 'INSIDE_SALES',
    LIDER = 'LIDER',
    LIDER_DE_CONFRONTO = 'LIDER_DE_CONFRONTO',
    LIDER_DE_MASTERCLASS = 'LIDER_DE_MASTERCLASS',
    LIDER_DE_EVENTOS = 'LIDER_DE_EVENTOS',
    LOGISTICA = 'LOGISTICA',
    PALESTRANTE = 'PALESTRANTE',
    RELACIONAMENTO_COM_CLIENTES = 'RELACIONAMENTO_COM_CLIENTES',
    SOCIAL_MEDIA = 'SOCIAL_MEDIA',
    SOCIAL_SELLING = 'SOCIAL_SELLING',
    STAFF = 'STAFF',
    TRAFEGO_DIGITAL = 'TRAFEGO_DIGITAL',
    TUTOR_MISSAO = 'TUTOR_MISSAO',
    VENDEDOR = 'VENDEDOR',
    WEB_DESIGNER = 'WEB_DESIGNER',
}

export enum EOrigemAlunos {
    ALUNO_BONUS = 'ALUNO_BONUS',
    ALUNO_CONVIDADO = 'ALUNO_CONVIDADO',
    COMPROU_INGRESSO = 'COMPROU_INGRESSO',
    CORTESIA = 'CORTESIA',
    PRESENTE = 'PRESENTE',
    SORTEIO = 'SORTEIO',
    TRANSFERENCIA = 'TRANSFERENCIA',
}

/** Motivo/categoria obrigatória ao excluir um contrato no Histórico de Vendas. */
export enum ECategoriaExclusaoContrato {
    ERRO_PREENCHIMENTO = 'ERRO_PREENCHIMENTO',
    CANCELAMENTO_ALUNO = 'CANCELAMENTO_ALUNO',
    OUTRO_MOTIVO = 'OUTRO_MOTIVO',
}

export enum EPresencaTurmas {
    NO_SHOW = 'NO_SHOW',
    PRESENTE = 'PRESENTE',
}

export enum EProfissao {
    CLT = 'CLT',
    DESEMPREGADO = 'DESEMPREGADO',
    EMPRESARIO = 'EMPRESARIO',
    FUNCIONARIO_PUBLICO = 'FUNCIONARIO_PUBLICO',
    LIDER = 'LIDER',
    PROFISSIONAL_LIBERAL = 'PROFISSIONAL_LIBERAL',
}

export enum EStatusAlunosGeral {
    ATIVO = 'ATIVO',
    INADIMPLENTE = 'INADIMPLENTE',
    INATIVO = 'INATIVO',
    PENDENTE = 'PENDENTE',
    SUSPENSO = 'SUSPENSO',
    CANCELADO = 'CANCELADO',
}

export enum EStatusAlunosTurmas {
    AGUARDANDO_CHECKIN = 'AGUARDANDO_CHECKIN',
    AGUARDANDO_CONFIRMACAO = 'AGUARDANDO_CONFIRMACAO',
    CANCELADO = 'CANCELADO',
    CHECKIN_REALIZADO = 'CHECKIN_REALIZADO',
    FALTA_ENVIAR_LINK_CONFIRMACAO = 'FALTA_ENVIAR_LINK_CONFIRMACAO',
}

export enum EStatusAssinaturasContratos {
    ASSINADO = 'ASSINADO',
    ASSINATURA_PENDENTE = 'ASSINATURA_PENDENTE',
    PARCIALMENTE_ASSINADO = 'PARCIALMENTE_ASSINADO',
}

export enum EStatusTurmas {
    AGUARDANDO_LIBERACAO = 'AGUARDANDO_LIBERACAO',
    ENCERRADA = 'ENCERRADA',
    INSCRICOES_ABERTAS = 'INSCRICOES_ABERTAS',
    INSCRICOES_PAUSADAS = 'INSCRICOES_PAUSADAS',
}

/**
 * Status do evento/masterclass no calendário (cores da legenda).
 * É salvo na turma. Eventos usam todos, exceto MC_EXTRA (exclusivo de masterclass).
 * Novo evento nasce em VERIFICAR_LOCAL; masterclasses vêm com o status do webhook.
 */
export enum EStatusEventoCalendario {
    OK = 'OK', // 100% OK (verde)
    VERIFICAR_LOCAL = 'VERIFICAR_LOCAL', // vermelho (padrão de eventos novos)
    PENDENCIAS = 'PENDENCIAS', // Com pendências (amarelo)
    CANCELADA = 'CANCELADA', // Cancelada ou adiada (roxo)
    MC_EXTRA = 'MC_EXTRA', // MC extra (azul) — só masterclass
}

export enum ETiposProdutos {
    LIVRO = 'LIVRO',
    MATERIAL_ESCRITORIO = 'MATERIAL_ESCRITORIO',
    OUTRO = 'OUTRO',
    VESTUARIO = 'VESTUARIO',
}

export enum ETipoDocumento {
    CONTRATO = 'CONTRATO',
    TERMO = 'TERMO',
}

export enum ETipoVinculoAluno {
    BONUS = 'BONUS',
    CONVIDADO = 'CONVIDADO',
}
